services:

  postgres:
    image: postgres:16-alpine
    container_name: productos-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: productosdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d productosdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: productos-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/productosdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      JWT_SECRET: uUmmOg0dohj/JCi7V0WY5EEECAg3HoAZAdaj2FPLRftM/yGGZXKHSKTRNNywXbeark3qgcJ15Mcx74vUdNHygA==
      JWT_EXPIRATION: 86400000
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ../productos-frontend
      dockerfile: Dockerfile
    container_name: productos-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
