spring.datasource.url=jdbc:postgresql://localhost:5432/productosdb
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET:uUmmOg0dohj/JCi7V0WY5EEECAg3HoAZAdaj2FPLRftM/yGGZXKHSKTRNNywXbeark3qgcJ15Mcx74vUdNHygA==}
jwt.expiration=${JWT_EXPIRATION:86400000}

server.port=${PORT:8080}